import { createClient } from "@/lib/supabase/server";
import type { Database } from "@/types/database";

export type Notification = Database["public"]["Tables"]["notifications"]["Row"];

export async function listNotifications(limit = 25): Promise<Notification[]> {
  const supabase = await createClient();
  const { data: auth } = await supabase.auth.getUser();
  if (!auth.user) return [];

  const { data, error } = await supabase
    .from("notifications")
    .select("*")
    .eq("user_id", auth.user.id)
    .order("created_at", { ascending: false })
    .limit(limit);

  if (error) {
    if (error.code === "42P01") return []; // Table not created yet — don't explode.
    console.error("[lumina] listNotifications:", error.message);
    return [];
  }
  return data ?? [];
}

export async function unreadCount(): Promise<number> {
  const supabase = await createClient();
  const { data: auth } = await supabase.auth.getUser();
  if (!auth.user) return 0;

  const { count, error } = await supabase
    .from("notifications")
    .select("*", { count: "exact", head: true })
    .eq("user_id", auth.user.id)
    .eq("read", false);

  if (error) {
    if (error.code === "42P01") return 0;
    console.error("[lumina] unreadCount:", error.message);
    return 0;
  }
  return count ?? 0;
}

/**
 * Insert a notification addressed to a specific user. Used by the manual
 * reminder flow; the primary booking/status notifications are generated by
 * Postgres triggers so they fire regardless of which client wrote.
 */
export async function createNotification(args: {
  userId: string;
  message: string;
  type?: string;
  appointmentId?: string;
}): Promise<{ error: string | null }> {
  const supabase = await createClient();
  const { error } = await supabase.from("notifications").insert({
    user_id: args.userId,
    message: args.message,
    type: args.type ?? "info",
    appointment_id: args.appointmentId ?? null,
  });
  if (error) {
    console.error("[lumina] createNotification:", error.message);
    return { error: error.message };
  }
  return { error: null };
}

export async function markAllRead(): Promise<{ error: string | null }> {
  const supabase = await createClient();
  const { data: auth } = await supabase.auth.getUser();
  if (!auth.user) return { error: "Not authenticated" };
  const { error } = await supabase
    .from("notifications")
    .update({ read: true })
    .eq("user_id", auth.user.id)
    .eq("read", false);
  if (error) {
    console.error("[lumina] markAllRead:", error.message);
    return { error: error.message };
  }
  return { error: null };
}
